### ISSUE TITLE
Exception is thrown when consecutively running a circuit

### ISSUE THREAD

**Issue by louislefevre** [louislefevre/node-red-contrib-quantum#31]
### Bug Description
An exception is thrown when running a circuit multiple times in a row, despite no changes being made.

### Steps to Reproduce Bug
Keep running the flow repeatedly, and eventually (often during the second run) execution fails due to an uncaught exception will be thrown.

### Expected Behaviour & Actual Behaviour
Expected behaviour is that the flow should run again and execute successfully, as there isn't any reason it should fail the second time since nothing has changed.

### Additional Information
Flow JSON:
https://pastebin.com/c3Avd7N2

Exception output:
```
[red] Uncaught Exception:
Error: Only qubits from a single quantum circuit should be connected to the simulator node.
    at SimulatorNode._inputCallback (/home/louis/projects/node-red-contrib-quantum/quantum/nodes/simulator/simulator.js:34:17)
    at /home/louis/projects/node-red-contrib-quantum/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26
    at Object.trigger (/home/louis/projects/node-red-contrib-quantum/node_modules/@node-red/runtime/lib/hooks.js:113:9)
    at SimulatorNode.Node._emitInput (/home/louis/projects/node-red-contrib-quantum/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)
    at SimulatorNode.Node.emit (/home/louis/projects/node-red-contrib-quantum/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)
    at SimulatorNode.Node.receive (/home/louis/projects/node-red-contrib-quantum/node_modules/@node-red/runtime/lib/nodes/Node.js:476:10)
    at Immediate.<anonymous> (/home/louis/projects/node-red-contrib-quantum/node_modules/@node-red/runtime/lib/flows/Flow.js:679:52)
    at processImmediate (node:internal/timers:464:21)
```

### System Information
* **Node.js Version**: 16.5.0
* **Operating System**: Arch Linux 5.12.15

**Comment by Theo-Reignier** [comment]
Solved in my new PR. #37  
Thanks Louis.
